name: hw1_env
dependencies:
  - python
  - pip
  - pip:
    - pandas==1.5.3
    - tqdm==4.65.0
    - torch==1.13.1
    - kornia==0.6.12
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - seaborn==0.11.2
    - matplotlib==3.7.1
    - numpy==1.24.3